branch-defaults:
  default:
    environment: Sample-env
    group_suffix: null
global:
  application_name: MyMessage
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: null
deploy:
  artifact: my-message.zip